site_name: Modular Object-Oriented Dynamic Learning Environment
site_url: https://Requisitos-de-Software.github.io/2022.2-Moodle/

theme:
  name: material
  language: pt
  logo: https://user-images.githubusercontent.com/79341819/202909824-0650cfef-d62b-46bb-8517-131ff9d71817.png
  favicon: https://user-images.githubusercontent.com/79341819/202906275-e2771845-ba44-470d-81cd-0270bf5444f1.png
  palette:
    scheme: slate
    primary: orange
    accent: orange
  features:
  - navigation.tabs
  - navigation.tabs.sticky
nav:
  - Início: index.md
  - Apresentações: apresentacoes.md
  - Planejamento:
    - Cronograma de reuniões: Planejamento/cronograma_reunioes.md
    - Cronograma de atividades: Planejamento/cronograma_atividades.md
    - Gerenciamento de riscos: Planejamento/gerenciamento_de_riscos.md
    - Ferramentas: Planejamento/ferramentas.md
    - Medotologia: Planejamento/metodologia.md
    - Reuniões: Planejamento/reunioes.md
  - Pré-Rastreabilidade:
    - Aplicativos avaliados: Pre_Rastreabilidade/apps_avaliados.md
    - RichPicture: Pre_Rastreabilidade/rich_picture.md
  - Elicitação:
    - Introdução: Elicitacao/elicitacao_de_requisitos.md
    - Personas: Elicitacao/personas.md
    - StoryTelling: Elicitacao/storytelling.md
    - Introspecção: Elicitacao/introspeccao.md
    - Observação: Elicitacao/observacao_etnografia.md
    - Questionário: Elicitacao/questionario.md
    - Requisitos Elicitados: Elicitacao/requisitos.md
  - Priorização:
    - Introdução: Priorização/priorizacao.md
    - First Things First: Priorização/First-Things-First.md
    - In or Out: Priorização/In-or-Out.md
  - Modelagem:
    - Cenários: Modelagem/cenarios.md
    - Casos de Uso: Modelagem/caso-de-uso.md
    - Especificação Suplementar: Modelagem/suplementar.md
    - Léxicos: Modelagem/lexicos.md
    - Histórias de Usuário: Modelagem/historias_usuario.md
    - Modelagem/backlog.md