site_name: Moodle

theme:
  name: material

  palette:
    scheme: slate
    primary: deep orange
  
  language: pt

  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - Inicio: index.md
  
  - Planejamento:
    - Escolha do app: planejamento/escolha_site.md
    - Ferramentas: planejamento/ferramentas.md
    - Cronograma: planejamento/cronograma.md
